server:
  servlet:
    context-path: /api/rest
  port: 3000
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
  datasource:
    username: root
    password: cartogo
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cartogo?characterEncoding=utf8&useUnicode=true

logging:
  level:
    root: debug

google.clientId: ${GOOGLE_CLIENT_ID}
jwt.secret: ${JWT_SECRET:abcdefghijklmnOPQRSTUVWXYZabcdefghijklmnOPQRSTUVWXYZabcdefghijklmnOPQRSTUVWXYZabcdefghijklmnOPQRSTUVWXYZabcdefghijklmnOPQRSTUVWXYZ}
